# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - testlscwebapp-03

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # 권한부여 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: tkg-pjt
        
      # Gradle 빌드 수정
      - name: Build with Gradle
        run : |
          cd tkg-pjt # 해당 디렉토리로 이동
          ./gradlew build -x test # Gradle 빌드 실행

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/tkg-pjt/build/libs/*.jar'
          
      # artifact 생성 확인
      - name: List files in build/libs directory
        run: ls tkg-pjt/build/libs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testlscwebapp-03'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7BA9304E17424626B879DC408AD36B43 }}
          package: '*.jar'
